/*LeetCode Logo
Problem List
0

avatar
Description
Editorial
Editorial
Solutions
Solutions
Submissions
Submissions


Code
Testcase
Test Result
Test Result
389. Find the Difference
Easy
Topics
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
Seen this question in a real interview before?
1/5
Yes
No
Accepted
838.9K
Submissions
1.4M
Acceptance Rate
59.5%
Topics
Companies
Similar Questions
Discussion (99)

Choose a type



Copyright ©️ 2025 LeetCode All rights reserved

5.1K


99



26 Online
C++
Auto





123456
class Solution {
public:
    char findTheDifference(string s, string t) {
        
    }
};
Saved

Case 1
Case 2

s =
"abcd"
t =
"abcde"

*/
//code
class Solution {
 public:
  char findTheDifference(string s, string t) {
    const char sXors = accumulate(s.begin(), s.end(), 0, bit_xor<>());
    const char tXors = accumulate(t.begin(), t.end(), 0, bit_xor<>());
    return sXors ^ tXors;
  }
};